[package]
name = "nova"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rpc-server"
path = "src/rpc/server.rs"

[[bin]]
name = "rpc-client"
path = "src/rpc/client.rs"

[[bin]]
name = "cmd"
path = "src/cmd/main.rs"


[dependencies]
clap = "3.2.16"
log = "0.4.17"
multi_log = "0.1.2"
simplelog = "0.12.0"
syslog = "6.0.1"
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
futures = "0.3.23"
tokio-stream = "0.1.9"
h2 = "0.3.13"

[build-dependencies]
tonic-build = "0.8"

